language: cpp
dist: xenial
compiler: clang
os: linux
before_install: 
  - sudo apt-get install ninja-build
script:
  - echo $PATH
  - echo "Building Ubuntu Xenial CLANG Natives"
  - mkdir build
  - cd build
  - cmake -G Ninja -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - cmake --build . -- -v
#  - ctest
